version: '3'
 
services:

  mosquitto:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./data/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf


  panduza-platform:
    container_name: panduza-cxx-platform
    image: ghcr.io/panduza/panduza-cxx-platform:latest
    user: builder
    network_mode: host
    privileged: true
    volumes:
      - ./data/panduza/tree.json:/etc/panduza/tree.json
      - ./data/bsdl:/etc/BoundaryScan
      - ./logs:/panduza-cxx-platform/logs

